# Generated by Django 5.0.6 on 2024-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_score_movie_score_rename_title_movie_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovieID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
